homes: {}

hello_message: "&aHello, world!"
max_homes_reached: "&cYou have reached the maximum number of homes."
home_set: "&aHome {home} set!"
teleport_home: "&aTeleported to home {home}!"
home_not_set: "&cHome {home} not set. Use /addhome to set it."
home_removed: "&aHome {home} removed!"
teleport_spawn: "&aTeleported to spawn!"
broadcast_prefix: "&6[Broadcast] &r"
broadcast_no_message: "&cPlease provide a message to broadcast."
only_players: "Only players can use this command."
specify_home_name: "&cPlease specify a home name."
no_homes_set: "&cYou have no homes set."
homes_list_prefix: "&aYour homes: "
config_reloaded: "&aConfiguration reloaded!"
join_message: "&a{player} joined the game!"
quit_message: "&c{player} left the game!"

balance: "&aYour balance: {balance}"
balance_other: "&aBalance of {player}: {balance}"
player_not_found: "&cPlayer not found."
usage_pay: "&cUsage: /pay <player> <amount>"
usage_give: "&cUsage: /give <player> <amount>"
usage_setbalance: "&cUsage: /setbalance <player> <amount>"
invalid_amount: "&cInvalid amount."
insufficient_funds: "&cInsufficient funds."
payment_sent: "&aYou sent {amount} to {player}."
payment_received: "&aYou received {amount} from {player}."
money_given: "&aYou gave {amount} to {player}."
money_received: "&aYou received {amount} from {player}."
balance_set: "&aBalance of {player} set to {amount}."
balance_updated: "&aYour balance has been updated to {amount} by {player}."
